# -*- coding: utf-8 -*-
"""linear_reg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vrzsx1aO2wtZJLI_qAlwvo3F5uF4jjW4
"""

from sklearn.linear_model import LinearRegression

import numpy as np

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

import matplotlib.pyplot as plt

x = np.array([[1], [2], [3], [4], [5]])

y = np.array([0, 0, 0, 70, 80])

model = LinearRegression()

model.fit(x, y)

print(float(model.coef_))
print(model.intercept_)

plt.scatter(x, y)

validation_data = np.random.randint(0, 10, 20)
validation_data

predictions = np.zeros_like(validation_data)

for index, var in enumerate(validation_data):
    got: np.float32 = model.predict([[var]])
    predictions[index] = got[0]

print(predictions)

fig = plt.figure()
ax = fig.add_subplot()

ax.set_xlim(0, max(validation_data))
ax.set_ylim(1, 200)

ax.plot(x, y, linestyle="--", color="green")
ax.plot(validation_data, predictions, marker="o")

plt.show()